export const UPDATE_RESPONSE = "UPDATE_RESPONSE";
export const UPDATE_LOGGED_IN = "UPDATE_LOGGED_IN";
export const UPDATE_CITIES = "UPDATE_CITIES";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_POPULAR_VENUES = "UPDATE_POPULAR_VENUES";
export const UPDATE_FEATURED_VENUE_LOCATION = "UPDATE_FEATURED_VENUE_LOCATION";
export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_ITEMS = "UPDATE_ITEMS";
