export const UPDATE_RESPONSE = "UPDATE_RESPONSE";
export const UPDATE_LOGGED_IN = "UPDATE_LOGGED_IN";
export const UPDATE_CITIES = "UPDATE_CITIES";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
